name: "Enrich Company Profile"
description: "Takes a company name and uses a custom code step to simulate fetching firmographic data."

inputs:
  - name: "company_name"
    type: "text"
    label: "Company Name to Enrich:"

steps:
  - name: "fetch_company_data_code"
    type: "code"
    dependencies: []
    params:
      function_name: "data_enrichment.EnrichCompanyProfileStep"
      input_key: "company_name"
      output_key: "enriched_profile"