name: "Extract Contact Details from Message"
description: "Takes a raw user message and uses an LLM to extract structured contact information."

inputs:
  - name: "user_message"
    type: "text"
    label: "Raw user inquiry message:"

steps:
  - name: "extract_details_llm"
    type: "llm"
    dependencies: []
    params:
      prompt_template: "1_extract_info.txt"
      input_mapping:
        user_message: "user_message"
      output_key: "extracted_data"