name: "Standard Dynamic Analysis Workflow"
description: "A declarative workflow demonstrating parallel execution and dependencies using only text input."

inputs:
  - name: "user_message"
    type: "text"
    label: "Enter User Message:"
    default: "The new USB-C port is great, but the battery life seems worse."

steps:
  - name: "initial_analysis"
    type: "llm"
    dependencies: []
    params:
      prompt_template: "1_initial_analysis.txt"
      input_mapping:
        user_message: "user_message"
      output_key: "initial_analysis_result"

  - name: "validate_user_message"
    type: "code"
    dependencies: []
    params:
      # UPDATED: Using the fully qualified class name
      function_name: "validation.IsMessageLongEnoughStep"
      input_key: "user_message"
      output_key: "validation_result"

  - name: "fetch_user_profile"
    type: "code"
    dependencies:
      - "initial_analysis_result"
    params:
      # UPDATED: Using the fully qualified class name
      function_name: "user_profile.GetUserProfileByIntentStep"
      input_key: "initial_analysis_result"
      output_key: "user_profile"

  - name: "strategist"
    type: "llm"
    dependencies:
      - "initial_analysis_result"
      - "validation_result"
      - "user_profile"
    params:
      prompt_template: "3_strategist.txt"
      input_mapping:
        analysis_result: "initial_analysis_result"
        # The output of the Pydantic model is a dict: {"is_long_enough": true}
        is_valid: "validation_result" 
        # The output of the Pydantic model is a dict: {"profile": {...}}
        profile: "user_profile"
      output_key: "final_strategy"