name: "Master Orchestrator Workflow"
description: "A master workflow that composes other workflows to handle a complex task."

inputs:
  - name: "main_user_message"
    type: "text"
    label: "Enter User Message:"
    default: "Please summarize the key findings in the attached document regarding the new product."
  - name: "main_document"
    type: "file"
    label: "Upload Supporting Document (Image or PDF):"

steps:
  # Step 1: Run the standard analysis on the text part.
  - name: "run_text_analysis"
    type: "workflow"
    dependencies: [] # Starts immediately with the initial inputs
    params:
      workflow_name: "standard_analysis"
      # Map from THIS workflow's state to the SUB-workflow's required inputs.
      input_mapping:
        main_user_message: "user_message" # parent_state['main_user_message'] -> sub_state['user_message']
      # Map from the SUB-workflow's final state back to THIS workflow's state.
      output_mapping:
        final_strategy: "text_analysis_strategy" # sub_state['final_strategy'] -> parent_state['text_analysis_strategy']

  # Step 2: Run the multimodal Q&A on the document.
  - name: "run_document_qa"
    type: "workflow"
    dependencies: []
    params:
      workflow_name: "multimodal_qa"
      input_mapping:
        main_user_message: "user_query"
        main_document: "context_document"
      output_mapping:
        extracted_summary: "document_summary"

  # Step 3: A final LLM call that uses the outputs of BOTH sub-workflows.
  - name: "synthesize_final_result"
    type: "llm"
    dependencies:
      - "text_analysis_strategy"
      - "document_summary"
    params:
      prompt_template: "1_synthesis.txt" # This prompt is local to this workflow package
      input_mapping:
        strategy: "text_analysis_strategy"
        summary: "document_summary"
      output_key: "final_synthesized_answer"