name: "8. JSON Input & Table Output Example"
description: "Demonstrates using the 'json' input type and the 'table' display hint for adaptive output visualization."
inputs:
  - name: "user_list_json"
    type: "json"
    label: "User Data (JSON Array):"
    default:
      - name: "Alice"
        role: "Engineer"
      - name: "Bob"
        role: "Designer"
      - name: "Charlie"
        role: "PM"

# Provide a hint to the UI to render the final output as a table.
outputs:
  - name: "processed_users"
    display_hint: "table"

steps:
  - name: "add_status_to_users"
    type: "code"
    dependencies: []
    params:
      function_name: "data_processing.AddStatusToUsersStep"
      input_mapping:
        user_list: "user_list_json"
      output_key: "processed_users"