name: "Multimodal Document Q&A Workflow"
description: "A workflow that takes a file (image or PDF) and a text query to perform analysis."

inputs:
  - name: "user_query"
    type: "text"
    label: "Your question about the document:"
    default: "Summarize the key findings in this document."
  - name: "context_document"
    type: "file"
    label: "Upload Document (Image or PDF):"

steps:
  - name: "document_analysis"
    type: "llm"
    dependencies: []
    params:
      prompt_template: "4_multimodal_analysis.txt"
      input_mapping:
        user_question: "user_query"
        document: "context_document"
      output_key: "analysis_of_document"

  - name: "extract_summary"
    type: "code"
    dependencies:
      - "analysis_of_document"
    params:
      # UPDATED: Using the fully qualified class name
      function_name: "data_processing.ExtractKeyFromDictStep"
      # The input model for this step expects a dict with a key 'data'
      input_key: "analysis_of_document" 
      output_key: "extracted_summary"